# This is a basic workflow to help you get started with Actions

name: CloudFlare

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          email: ${{ secrets.EMAIL }}
          key: ${{ secrets.KEY }}
        run: |
          echo Add other actions to build,
          curl --location --request PUT 'https://api.cloudflare.com/client/v4/zones/eb0c3244fbc7d9eb1581d0d0c11e2596/custom_pages/1000_errors' \
          --header 'X-Auth-Email: ${{ secrets.EMAIL }}' \
          --header 'X-Auth-Key: ${{ secrets.KEY }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{"url": "http://sorry.cubiksonline.us/index.html","state": "customized"
              }'
          echo test, and deploy your project.
